export interface Country {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
}

export interface CountryOption extends Country {
  label: string;
}

export const WORLD_COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afganistan', dialCode: '+93', flag: '🇦🇫' },
  { code: 'DE', name: 'Almanya', dialCode: '+49', flag: '🇩🇪' },
  { code: 'US', name: 'Amerika Birleşik Devletleri', dialCode: '+1', flag: '🇺🇸' },
  { code: 'AD', name: 'Andorra', dialCode: '+376', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', dialCode: '+244', flag: '🇦🇴' },
  { code: 'AI', name: 'Anguilla', dialCode: '+1264', flag: '🇦🇮' },
  { code: 'AQ', name: 'Antarktika', dialCode: '+672', flag: '🇦🇶' },
  { code: 'AG', name: 'Antigua ve Barbuda', dialCode: '+1268', flag: '🇦🇬' },
  { code: 'AR', name: 'Arjantin', dialCode: '+54', flag: '🇦🇷' },
  { code: 'AL', name: 'Arnavutluk', dialCode: '+355', flag: '🇦🇱' },
  { code: 'AW', name: 'Aruba', dialCode: '+297', flag: '🇦🇼' },
  { code: 'AU', name: 'Avustralya', dialCode: '+61', flag: '🇦🇺' },
  { code: 'AT', name: 'Avusturya', dialCode: '+43', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaycan', dialCode: '+994', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamalar', dialCode: '+1242', flag: '🇧🇸' },
  { code: 'BH', name: 'Bahreyn', dialCode: '+973', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladeş', dialCode: '+880', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', dialCode: '+1246', flag: '🇧🇧' },
  { code: 'BY', name: 'Belarus', dialCode: '+375', flag: '🇧🇾' },
  { code: 'BE', name: 'Belçika', dialCode: '+32', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', dialCode: '+501', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benin', dialCode: '+229', flag: '🇧🇯' },
  { code: 'BM', name: 'Bermuda', dialCode: '+1441', flag: '🇧🇲' },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', flag: '🇧🇹' },
  { code: 'AE', name: 'Birleşik Arap Emirlikleri', dialCode: '+971', flag: '🇦🇪' },
  { code: 'GB', name: 'Birleşik Krallık', dialCode: '+44', flag: '🇬🇧' },
  { code: 'BO', name: 'Bolivya', dialCode: '+591', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosna-Hersek', dialCode: '+387', flag: '🇧🇦' },
  { code: 'BW', name: 'Botsvana', dialCode: '+267', flag: '🇧🇼' },
  { code: 'BR', name: 'Brezilya', dialCode: '+55', flag: '🇧🇷' },
  { code: 'BN', name: 'Brunei', dialCode: '+673', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgaristan', dialCode: '+359', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', dialCode: '+257', flag: '🇧🇮' },
  { code: 'CV', name: 'Cabo Verde', dialCode: '+238', flag: '🇨🇻' },
  { code: 'GI', name: 'Cebelitarık', dialCode: '+350', flag: '🇬🇮' },
  { code: 'DZ', name: 'Cezayir', dialCode: '+213', flag: '🇩🇿' },
  { code: 'DJ', name: 'Cibuti', dialCode: '+253', flag: '🇩🇯' },
  { code: 'TD', name: 'Çad', dialCode: '+235', flag: '🇹🇩' },
  { code: 'CZ', name: 'Çekya', dialCode: '+420', flag: '🇨🇿' },
  { code: 'CN', name: 'Çin', dialCode: '+86', flag: '🇨🇳' },
  { code: 'DK', name: 'Danimarka', dialCode: '+45', flag: '🇩🇰' },
  { code: 'CD', name: 'Demokratik Kongo Cumhuriyeti', dialCode: '+243', flag: '🇨🇩' },
  { code: 'DO', name: 'Dominik Cumhuriyeti', dialCode: '+1809', flag: '🇩🇴' },
  { code: 'DM', name: 'Dominika', dialCode: '+1767', flag: '🇩🇲' },
  { code: 'EC', name: 'Ekvador', dialCode: '+593', flag: '🇪🇨' },
  { code: 'GQ', name: 'Ekvator Ginesi', dialCode: '+240', flag: '🇬🇶' },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', flag: '🇸🇻' },
  { code: 'ID', name: 'Endonezya', dialCode: '+62', flag: '🇮🇩' },
  { code: 'ER', name: 'Eritre', dialCode: '+291', flag: '🇪🇷' },
  { code: 'AM', name: 'Ermenistan', dialCode: '+374', flag: '🇦🇲' },
  { code: 'EE', name: 'Estonya', dialCode: '+372', flag: '🇪🇪' },
  { code: 'SZ', name: 'Esvatini', dialCode: '+268', flag: '🇸🇿' },
  { code: 'ET', name: 'Etiyopya', dialCode: '+251', flag: '🇪🇹' },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', flag: '🇫🇯' },
  { code: 'CI', name: 'Fildişi Sahili', dialCode: '+225', flag: '🇨🇮' },
  { code: 'PH', name: 'Filipinler', dialCode: '+63', flag: '🇵🇭' },
  { code: 'PS', name: 'Filistin', dialCode: '+970', flag: '🇵🇸' },
  { code: 'FI', name: 'Finlandiya', dialCode: '+358', flag: '🇫🇮' },
  { code: 'FR', name: 'Fransa', dialCode: '+33', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', dialCode: '+241', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambiya', dialCode: '+220', flag: '🇬🇲' },
  { code: 'GH', name: 'Gana', dialCode: '+233', flag: '🇬🇭' },
  { code: 'GN', name: 'Gine', dialCode: '+224', flag: '🇬🇳' },
  { code: 'GW', name: 'Gine-Bissau', dialCode: '+245', flag: '🇬🇼' },
  { code: 'GD', name: 'Grenada', dialCode: '+1473', flag: '🇬🇩' },
  { code: 'GL', name: 'Grönland', dialCode: '+299', flag: '🇬🇱' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', flag: '🇬🇹' },
  { code: 'GY', name: 'Guyana', dialCode: '+592', flag: '🇬🇾' },
  { code: 'ZA', name: 'Güney Afrika', dialCode: '+27', flag: '🇿🇦' },
  { code: 'KR', name: 'Güney Kore', dialCode: '+82', flag: '🇰🇷' },
  { code: 'SS', name: 'Güney Sudan', dialCode: '+211', flag: '🇸🇸' },
  { code: 'GE', name: 'Gürcistan', dialCode: '+995', flag: '🇬🇪' },
  { code: 'HT', name: 'Haiti', dialCode: '+509', flag: '🇭🇹' },
  { code: 'IN', name: 'Hindistan', dialCode: '+91', flag: '🇮🇳' },
  { code: 'HR', name: 'Hırvatistan', dialCode: '+385', flag: '🇭🇷' },
  { code: 'NL', name: 'Hollanda', dialCode: '+31', flag: '🇳🇱' },
  { code: 'HN', name: 'Honduras', dialCode: '+504', flag: '🇭🇳' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰' },
  { code: 'IQ', name: 'Irak', dialCode: '+964', flag: '🇮🇶' },
  { code: 'IR', name: 'İran', dialCode: '+98', flag: '🇮🇷' },
  { code: 'IE', name: 'İrlanda', dialCode: '+353', flag: '🇮🇪' },
  { code: 'ES', name: 'İspanya', dialCode: '+34', flag: '🇪🇸' },
  { code: 'IL', name: 'İsrail', dialCode: '+972', flag: '🇮🇱' },
  { code: 'SE', name: 'İsveç', dialCode: '+46', flag: '🇸🇪' },
  { code: 'CH', name: 'İsviçre', dialCode: '+41', flag: '🇨🇭' },
  { code: 'IT', name: 'İtalya', dialCode: '+39', flag: '🇮🇹' },
  { code: 'IS', name: 'İzlanda', dialCode: '+354', flag: '🇮🇸' },
  { code: 'JM', name: 'Jamaika', dialCode: '+1876', flag: '🇯🇲' },
  { code: 'JP', name: 'Japonya', dialCode: '+81', flag: '🇯🇵' },
  { code: 'KH', name: 'Kamboçya', dialCode: '+855', flag: '🇰🇭' },
  { code: 'CM', name: 'Kamerun', dialCode: '+237', flag: '🇨🇲' },
  { code: 'CA', name: 'Kanada', dialCode: '+1', flag: '🇨🇦' },
  { code: 'ME', name: 'Karadağ', dialCode: '+382', flag: '🇲🇪' },
  { code: 'QA', name: 'Katar', dialCode: '+974', flag: '🇶🇦' },
  { code: 'KZ', name: 'Kazakistan', dialCode: '+7', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪' },
  { code: 'CY', name: 'Kıbrıs', dialCode: '+357', flag: '🇨🇾' },
  { code: 'KG', name: 'Kırgızistan', dialCode: '+996', flag: '🇰🇬' },
  { code: 'CO', name: 'Kolombiya', dialCode: '+57', flag: '🇨🇴' },
  { code: 'KM', name: 'Komorlar', dialCode: '+269', flag: '🇰🇲' },
  { code: 'CG', name: 'Kongo Cumhuriyeti', dialCode: '+242', flag: '🇨🇬' },
  { code: 'CR', name: 'Kosta Rika', dialCode: '+506', flag: '🇨🇷' },
  { code: 'KW', name: 'Kuveyt', dialCode: '+965', flag: '🇰🇼' },
  { code: 'KP', name: 'Kuzey Kore', dialCode: '+850', flag: '🇰🇵' },
  { code: 'MK', name: 'Kuzey Makedonya', dialCode: '+389', flag: '🇲🇰' },
  { code: 'CU', name: 'Küba', dialCode: '+53', flag: '🇨🇺' },
  { code: 'LA', name: 'Laos', dialCode: '+856', flag: '🇱🇦' },
  { code: 'LS', name: 'Lesoto', dialCode: '+266', flag: '🇱🇸' },
  { code: 'LV', name: 'Letonya', dialCode: '+371', flag: '🇱🇻' },
  { code: 'LR', name: 'Liberya', dialCode: '+231', flag: '🇱🇷' },
  { code: 'LY', name: 'Libya', dialCode: '+218', flag: '🇱🇾' },
  { code: 'LI', name: 'Lihtenştayn', dialCode: '+423', flag: '🇱🇮' },
  { code: 'LT', name: 'Litvanya', dialCode: '+370', flag: '🇱🇹' },
  { code: 'LB', name: 'Lübnan', dialCode: '+961', flag: '🇱🇧' },
  { code: 'LU', name: 'Lüksemburg', dialCode: '+352', flag: '🇱🇺' },
  { code: 'HU', name: 'Macaristan', dialCode: '+36', flag: '🇭🇺' },
  { code: 'MG', name: 'Madagaskar', dialCode: '+261', flag: '🇲🇬' },
  { code: 'MO', name: 'Makao', dialCode: '+853', flag: '🇲🇴' },
  { code: 'MY', name: 'Malezya', dialCode: '+60', flag: '🇲🇾' },
  { code: 'MW', name: 'Malavi', dialCode: '+265', flag: '🇲🇼' },
  { code: 'MV', name: 'Maldivler', dialCode: '+960', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', dialCode: '+223', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', dialCode: '+356', flag: '🇲🇹' },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', flag: '🇲🇺' },
  { code: 'MX', name: 'Meksika', dialCode: '+52', flag: '🇲🇽' },
  { code: 'EG', name: 'Mısır', dialCode: '+20', flag: '🇪🇬' },
  { code: 'FM', name: 'Mikronezya', dialCode: '+691', flag: '🇫🇲' },
  { code: 'MN', name: 'Moğolistan', dialCode: '+976', flag: '🇲🇳' },
  { code: 'MD', name: 'Moldova', dialCode: '+373', flag: '🇲🇩' },
  { code: 'MC', name: 'Monako', dialCode: '+377', flag: '🇲🇨' },
  { code: 'MR', name: 'Moritanya', dialCode: '+222', flag: '🇲🇷' },
  { code: 'MZ', name: 'Mozambik', dialCode: '+258', flag: '🇲🇿' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: '🇲🇲' },
  { code: 'NA', name: 'Namibya', dialCode: '+264', flag: '🇳🇦' },
  { code: 'NP', name: 'Nepal', dialCode: '+977', flag: '🇳🇵' },
  { code: 'NE', name: 'Nijer', dialCode: '+227', flag: '🇳🇪' },
  { code: 'NG', name: 'Nijerya', dialCode: '+234', flag: '🇳🇬' },
  { code: 'NI', name: 'Nikaragua', dialCode: '+505', flag: '🇳🇮' },
  { code: 'NO', name: 'Norveç', dialCode: '+47', flag: '🇳🇴' },
  { code: 'CF', name: 'Orta Afrika Cumhuriyeti', dialCode: '+236', flag: '🇨🇫' },
  { code: 'UZ', name: 'Özbekistan', dialCode: '+998', flag: '🇺🇿' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰' },
  { code: 'PA', name: 'Panama', dialCode: '+507', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua Yeni Gine', dialCode: '+675', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', dialCode: '+51', flag: '🇵🇪' },
  { code: 'PL', name: 'Polonya', dialCode: '+48', flag: '🇵🇱' },
  { code: 'PT', name: 'Portekiz', dialCode: '+351', flag: '🇵🇹' },
  { code: 'PR', name: 'Porto Riko', dialCode: '+1787', flag: '🇵🇷' },
  { code: 'RO', name: 'Romanya', dialCode: '+40', flag: '🇷🇴' },
  { code: 'RW', name: 'Ruanda', dialCode: '+250', flag: '🇷🇼' },
  { code: 'RU', name: 'Rusya', dialCode: '+7', flag: '🇷🇺' },
  { code: 'WS', name: 'Samoa', dialCode: '+685', flag: '🇼🇸' },
  { code: 'SM', name: 'San Marino', dialCode: '+378', flag: '🇸🇲' },
  { code: 'SN', name: 'Senegal', dialCode: '+221', flag: '🇸🇳' },
  { code: 'SC', name: 'Seyşeller', dialCode: '+248', flag: '🇸🇨' },
  { code: 'RS', name: 'Sırbistan', dialCode: '+381', flag: '🇷🇸' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapur', dialCode: '+65', flag: '🇸🇬' },
  { code: 'SK', name: 'Slovakya', dialCode: '+421', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenya', dialCode: '+386', flag: '🇸🇮' },
  { code: 'SO', name: 'Somali', dialCode: '+252', flag: '🇸🇴' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰' },
  { code: 'SD', name: 'Sudan', dialCode: '+249', flag: '🇸🇩' },
  { code: 'SR', name: 'Surinam', dialCode: '+597', flag: '🇸🇷' },
  { code: 'SY', name: 'Suriye', dialCode: '+963', flag: '🇸🇾' },
  { code: 'SA', name: 'Suudi Arabistan', dialCode: '+966', flag: '🇸🇦' },
  { code: 'CL', name: 'Şili', dialCode: '+56', flag: '🇨🇱' },
  { code: 'TJ', name: 'Tacikistan', dialCode: '+992', flag: '🇹🇯' },
  { code: 'TZ', name: 'Tanzanya', dialCode: '+255', flag: '🇹🇿' },
  { code: 'TH', name: 'Tayland', dialCode: '+66', flag: '🇹🇭' },
  { code: 'TW', name: 'Tayvan', dialCode: '+886', flag: '🇹🇼' },
  { code: 'TG', name: 'Togo', dialCode: '+228', flag: '🇹🇬' },
  { code: 'TO', name: 'Tonga', dialCode: '+676', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad ve Tobago', dialCode: '+1868', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunus', dialCode: '+216', flag: '🇹🇳' },
  { code: 'TR', name: 'Türkiye', dialCode: '+90', flag: '🇹🇷' },
  { code: 'TM', name: 'Türkmenistan', dialCode: '+993', flag: '🇹🇲' },
  { code: 'UG', name: 'Uganda', dialCode: '+256', flag: '🇺🇬' },
  { code: 'UA', name: 'Ukrayna', dialCode: '+380', flag: '🇺🇦' },
  { code: 'OM', name: 'Umman', dialCode: '+968', flag: '🇴🇲' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: '🇺🇾' },
  { code: 'JO', name: 'Ürdün', dialCode: '+962', flag: '🇯🇴' },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', flag: '🇻🇺' },
  { code: 'VA', name: 'Vatikan', dialCode: '+379', flag: '🇻🇦' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳' },
  { code: 'YE', name: 'Yemen', dialCode: '+967', flag: '🇾🇪' },
  { code: 'NZ', name: 'Yeni Zelanda', dialCode: '+64', flag: '🇳🇿' },
  { code: 'GR', name: 'Yunanistan', dialCode: '+30', flag: '🇬🇷' },
  { code: 'ZM', name: 'Zambiya', dialCode: '+260', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabve', dialCode: '+263', flag: '🇿🇼' }
];

/**
 * Returns world countries sorted alphabetically according to Turkish collation,
 * formatted with label containing flag, country name, and telephone dial code.
 */
export function getSortedCountryOptions(): CountryOption[] {
  return [...WORLD_COUNTRIES]
    .sort((a, b) => a.name.localeCompare(b.name, 'tr-TR'))
    .map(c => ({
      ...c,
      label: `${c.flag} ${c.name} (${c.dialCode})`
    }));
}
